"""add_image_url_to_pickups

Revision ID: 0f098c14480c
Revises: cfd365aca0ec
Create Date: 2025-12-06 14:55:30.657522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f098c14480c'
down_revision: Union[str, Sequence[str], None] = 'cfd365aca0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickups', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickups', 'image_url')
    # ### end Alembic commands ###
