"""added description in pickup item

Revision ID: 5ea2720eeaa8
Revises: e8c256a3feb4
Create Date: 2025-12-07 07:51:33.081559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea2720eeaa8'
down_revision: Union[str, Sequence[str], None] = 'e8c256a3feb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_items', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pickup_items', sa.Column('years_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_items', 'years_used')
    op.drop_column('pickup_items', 'description')
    # ### end Alembic commands ###
