"""changes in inventory and pickup

Revision ID: d7955045db56
Revises: eb74f22445fe
Create Date: 2025-12-06 20:37:39.502549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7955045db56'
down_revision: Union[str, Sequence[str], None] = 'eb74f22445fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('item_name', sa.String(), nullable=True))
    op.add_column('inventory_logs', sa.Column('category', sa.String(), nullable=True))
    op.add_column('inventory_logs', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('inventory_logs', sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'REFURBISHING', 'RECYCLED', name='inventorystatus'), nullable=True))
    op.add_column('inventory_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('inventory_logs', 'pickup_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('inventory_logs_pickup_id_key'), 'inventory_logs', type_='unique')
    op.drop_column('inventory_logs', 'certificate_url')
    op.drop_column('inventory_logs', 'warehouse_location')
    op.drop_column('inventory_logs', 'processing_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('processing_status', postgresql.ENUM('PENDING', 'REFURBISHING', 'RECYCLED', name='processingstatus'), autoincrement=False, nullable=True))
    op.add_column('inventory_logs', sa.Column('warehouse_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inventory_logs', sa.Column('certificate_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('inventory_logs_pickup_id_key'), 'inventory_logs', ['pickup_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('inventory_logs', 'pickup_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inventory_logs', 'created_at')
    op.drop_column('inventory_logs', 'status')
    op.drop_column('inventory_logs', 'value')
    op.drop_column('inventory_logs', 'category')
    op.drop_column('inventory_logs', 'item_name')
    # ### end Alembic commands ###
