"""update_models_inventory_logic

Revision ID: ea3c671ad284
Revises: d7955045db56
Create Date: 2025-12-07 04:08:48.238683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea3c671ad284'
down_revision: Union[str, Sequence[str], None] = 'd7955045db56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_items', 'status')
    op.alter_column('users', 'reset_token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token_expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('pickup_items', sa.Column('status', postgresql.ENUM('PENDING', 'RECEIVED', 'REFURBISHING', 'RECYCLED', name='inventorystatus'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
