"""add status to pickup_items

Revision ID: eb74f22445fe
Revises: f343905e3581
Create Date: 2025-12-06 20:09:43.527378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb74f22445fe'
down_revision: Union[str, Sequence[str], None] = 'f343905e3581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickup_items', sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'REFURBISHING', 'RECYCLED', name='inventorystatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_items', 'status')
    # ### end Alembic commands ###
