"""added timeslot in pickup

Revision ID: f343905e3581
Revises: 0f098c14480c
Create Date: 2025-12-06 15:38:05.948666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f343905e3581'
down_revision: Union[str, Sequence[str], None] = '0f098c14480c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickups', sa.Column('pickup_date', sa.Date(), nullable=True))
    op.add_column('pickups', sa.Column('timeslot', sa.String(), nullable=True))
    op.drop_column('pickups', 'scheduled_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickups', sa.Column('scheduled_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('pickups', 'timeslot')
    op.drop_column('pickups', 'pickup_date')
    # ### end Alembic commands ###
